### ISSUE TITLE
Designing Error 404 page 

### ISSUE THREAD

**Issue by ManpreetSingh18** [SurajSanap/College.ai-main#43]
When a user clicks on a page that is not defined an Error page should come to tell them and give option to redirect to the Home Page
Current scenario
![Screenshot 2024-06-02 173743](https://github.com/SurajSanap/College.ai-main/assets/72294811/c136a5ea-8822-403d-a5bf-f9c48012bdce)
Expected result
![Screenshot 2024-06-02 153718](https://github.com/SurajSanap/College.ai-main/assets/72294811/997b2819-aace-4037-b986-e8c17af0aa4c)

**Comment by SurajSanap** [comment]
Hi @ManpreetSingh18,

Thanks for your interest in our project, College.ai.

In this case, our webpage is capable of popping up an alert message and keeping the user on the home screen, so that's fine for now. We would like to contact you in the future if we require such contributions. Thanks again!

![ezgif-3-6c066b4b06](https://github.com/SurajSanap/College.ai-main/assets/101057653/d07f8d0a-1884-4e24-bf29-a097be4ddd3e)

**Comment by SurajSanap** [comment]
Hi @ManpreetSingh18,

Thanks for your interest in our project, College.ai.

In this case, our webpage is capable of popping up an alert message and keeping the user on the home screen, so that's fine for now. We would like to contact you in the future if we require such contributions. Thanks again!

![image](https://github.com/SurajSanap/College.ai-main/assets/101057653/7070e8fc-9ba5-4941-b695-2226e710dead)
